"""Task 1 - Ps and Qs attack  (15 points: 6 + 9)

  is_waldo(n1, n2)                        -> bool   6 points
  get_private_key_from_n1_n2_e(n1, n2, e) -> d      9 points

GOAL: two RSA moduli of this class share a prime factor.  Find the classmate
whose modulus shares a prime with yours, recover your own private exponent d
from public information only, and decrypt your flag
(it looks like CRYPTO{psqs_<your student number>}).

All the RSA public keys of this class were generated by the *same* broken
random number generator: when it was restarted it handed out a prime number
that another student had already used.  Two moduli that share a prime factor
can both be factored with a single gcd.

`inputs_task1.json` contains

    {"public_keys": {"<student number>": <N>, ...},      # the whole class
     "students":    {"<student number>": {"N": ..., "e": ..., "c": ...}}}

`public_keys` maps every student number (including yours) to a modulus, and
`students` holds your own public key together with a ciphertext `c` of your
flag.  Your flag is `CRYPTO{psqs_<your student number>}`.

Implement

  * `is_waldo(n1, n2)`: return True when the two moduli share a prime factor,
    otherwise False.  You need this to find the classmate who shares your
    prime ("Waldo").
  * `get_private_key_from_n1_n2_e(n1, n2, e)`: given your modulus `n1` and the
    modulus `n2` of that classmate, return your private exponent `d`.

Run `python3 test.py` to check yourself.  Only the Python standard library may
be used.
"""


def _gcd(a, b):
    while b:
        a, b = b, a % b
    return a


def _egcd(a, b):
    """Extended Euclidean algorithm: return (g, x, y) with a*x + b*y = g."""
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        quotient = old_r // r
        old_r, r = r, old_r - quotient * r
        old_s, s = s, old_s - quotient * s
        old_t, t = t, old_t - quotient * t
    return old_r, old_s, old_t


def _modinv(a, m):
    g, x, _ = _egcd(a, m)
    if g != 1:
        raise ValueError("no modular inverse: gcd(a, m) != 1")
    return x % m


def is_waldo(n1, n2):
    """Return True iff n1 and n2 share a non-trivial factor."""
    return _gcd(n1, n2) != 1


def get_private_key_from_n1_n2_e(n1, n2, e):
    """Return the private exponent d of the key (n1, e)."""
    p = _gcd(n1, n2)
    q = n1 // p
    lam = (p - 1) * (q - 1) // _gcd(p - 1, q - 1)
    d = _modinv(e, lam)
    return d


def get_student_number():
    return "3035987788"
